# Generated by Django 5.2 on 2025-08-01 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('referral_code', models.CharField(max_length=20, unique=True)),
                ('donations_raised', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LeaderboardEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('donations_raised', models.PositiveIntegerField(default=0)),
                ('intern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.intern')),
            ],
            options={
                'ordering': ['-donations_raised', 'rank'],
            },
        ),
    ]
