# Generated by Django 5.2 on 2025-08-04 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Intern',
            new_name='Internportal',
        ),
    ]
